# Minimal config for stripped-down MacPorts snmpd

# Run snmpd with this config:
# mkdir -p /tmp/snmp-persist
# SNMP_PERSISTENT_DIR=/tmp/snmp-persist snmpd -f -Lo -C -c ./snmpd.conf

# SNMPv1/v2c read-only community (rocommunity IS the right token here,
# the warning is harmless - it still works on some builds)
rocommunity  public  127.0.0.1

# System info
syslocation "My Mac"
syscontact  "test@example.com"

# Listen on localhost, unprivileged port
agentAddress udp:127.0.0.1:1161
